import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Manual sidebar configuration with hola.md as landing page
  tutorialSidebar: [
    'landing/devhood',
    {
      type: 'category',
      label: 'Desarrollo Web',
      items: [{type: 'autogenerated', dirName: 'desarrollo-web'}],
    },
    {
      type: 'category',
      label: 'Accesibilidad',
      items: [{type: 'autogenerated', dirName: 'accesibilidad'}],
    },
  ],
};

export default sidebars;
